### ISSUE TITLE
Unable to complete build on Debian 9

### ISSUE THREAD

**Issue by andy5995** [ajbogh/norman#2] opened 2018-08-30 22:56 UTC
The build fails on Debian 9.

https://gist.githubusercontent.com/andy5995/314a07e188a14597ab55885120adb764/raw/67d8d94acffcb3fe1d1d89e6dec1ebc4e0944977/gistfile1.txt

npm debug log

https://gist.githubusercontent.com/andy5995/74dd39db1053495f1cf98c6f5d8bac92/raw/a646bee81a662338129ee8fa06a53d00e5697eca/gistfile1.txt

**Comment by ajbogh** [comment] 2018-08-31 01:11
Thanks @andy5995. I've been dealing with the same issues on Ubuntu and hope to have a fix very soon. I believe it has something to do with installing the files in a different --prefix folder and not using `sudo`, but the error message is cryptic and isn't helping.

If by chance you find a fix and would like to submit a PR, I would very much appreciate it.

**Comment by andy5995** [comment] 2018-08-31 02:37
>If by chance you find a fix and would like to submit a PR, I would very much appreciate it.

Ok, done.

**Comment by andy5995** [comment] 2018-08-31 02:45
Actually.. a moment and I'll make that PR a little cleaner...

**Comment by ajbogh** [comment] 2018-09-01 19:38
I'm going to close this issue since the problem is fixed using the `-i` flag. While that may not be the best solution, it seems to work and I'm happy with it. If I find that other installations are causing problems I may revisit the PR above. I hope you don't mind.

**Closed as completed by ajbogh** 2018-09-01 19:38 UTC
Labels: bug
